"""B-1 — Risk-coverage figure + cost-to-target LaTeX table for Table 13.

Consumes the deferral_economics.json produced by
``src.thesis_evaluations.deferral_eval`` (deterministic post-hoc analysis of
the agentic-ablation per-question JSONLs — no model calls). Emits:

  * risk_coverage.png / .pdf  — selective-prediction risk-coverage curve
      (Geifman & El-Yaniv 2017, NeurIPS). x = coverage (fraction answered
      locally), y = risk (1 − Soft-EM) on the answered slice. A well-calibrated
      abstention signal makes risk fall as coverage shrinks (the model declines
      its likely-wrong answers first). Plotted as a step function because
      deferral proceeds in discrete confidence tiers.
  * table13_deferral.tex — cost-to-hit-accuracy-target table for the
      +Verifier config (the calibrated-confidence deferral policy), ready to
      \\input into the paper as Table 13.

Run:
    python -X utf8 scripts/plot_risk_coverage.py <deferral_economics.json> [-o OUTDIR]
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt  # noqa: E402

# The config whose confidence signal drives the deferral ranking. The verifier
# emits the categorical confidence used worst-first; this is the headline curve.
_HEADLINE_CONFIG = "+Verifier"


def _coverage_risk(points: list[dict]) -> tuple[list[float], list[float]]:
    """Map deferral points → (coverage, risk-on-answered-slice).

    coverage = fraction kept local (answered by the edge model) = 1 − defer.
    risk     = 1 − local-only accuracy on the kept slice. At coverage→0 the
    local-only accuracy is NaN (nothing kept); we drop those points so the
    curve is the honest selective-prediction risk of the *answered* set.
    """
    cov, risk = [], []
    for p in points:
        c = 1.0 - p["defer_fraction_actual"]
        a = p["accuracy_local_only"]
        if a is None or (isinstance(a, float) and math.isnan(a)):
            continue
        cov.append(c)
        risk.append(1.0 - a)
    # sort by ascending coverage for a clean left→right step plot
    order = sorted(range(len(cov)), key=lambda i: cov[i])
    return [cov[i] for i in order], [risk[i] for i in order]


def _plot(data: dict, out_dir: Path) -> Path:
    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    configs = data["configs"]

    # Plot every config faintly, headline config bold.
    for label, cfg in configs.items():
        cov, risk = _coverage_risk(cfg["points"])
        if not cov:
            continue
        if label == _HEADLINE_CONFIG:
            ax.step(cov, risk, where="post", linewidth=2.4, label=label, zorder=5)
        else:
            ax.step(cov, risk, where="post", linewidth=1.0, alpha=0.45, label=label)

    ax.set_xlabel("Coverage (fraction answered on-device)")
    ax.set_ylabel("Risk on answered slice  (1 − Soft-EM)")
    ax.set_title("Risk–coverage: calibrated abstention for edge RAG")
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(bottom=0.0)
    ax.grid(True, linestyle=":", alpha=0.5)
    ax.legend(fontsize=8, loc="upper left")
    fig.tight_layout()

    png = out_dir / "risk_coverage.png"
    pdf = out_dir / "risk_coverage.pdf"
    fig.savefig(png, dpi=200)
    fig.savefig(pdf)
    plt.close(fig)
    return png


_TEX_TEMPLATE = r"""% Generated by scripts/plot_risk_coverage.py — do not edit by hand.
% Cost to reach an accuracy target via worst-confidence-first edge→cloud
% deferral, {config} config, n={n}, HotpotQA. Cloud model assumed at
% {cloud_acc:.0%} Soft-EM on the deferred slice ({mode} mode);
% per-deferred-query cost ${cost_q:.4f} (in ${price_in}/Mtok, out ${price_out}/Mtok).
\begin{{table}}[t]
\centering
\caption{{Edge--cloud deferral economics for the \textbf{{{config}}} configuration:
cost to hit an accuracy target. Pure-edge Soft-EM is {pure_local:.1%}
(0\% deferral, \$0); pure-cloud ceiling is {pure_cloud:.1%}. Deferral is
worst-confidence-first using the verifier's calibrated signal. (Note: the
deferral table in findings_complete.md \S4.4 reports the \emph{{RAG (no agent)}}
row; this table reports \emph{{+Verifier}}, so the per-target \$ costs differ by
configuration.)}}
\label{{tab:deferral-economics}}
\begin{{tabular}}{{lrrrr}}
\toprule
Target Soft-EM & Reachable & Defer \% & Achieved & Cost / 1000q (USD) \\
\midrule
{rows}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def _table(data: dict, out_dir: Path) -> Path:
    cfg = data["configs"][_HEADLINE_CONFIG]
    rows = []
    for t in cfg["targets"]:
        reachable = "yes" if t["reachable"] else "no"
        defer_pct = f"{t['defer_fraction'] * 100:.1f}"
        achieved = f"{t['achieved_accuracy'] * 100:.1f}\\%" if t["reachable"] else "--"
        cost = f"{t['cost_usd_per_1000q']:.2f}" if t["reachable"] else "--"
        rows.append(
            f"{t['target_accuracy'] * 100:.0f}\\% & {reachable} & {defer_pct} & "
            f"{achieved} & {cost} \\\\"
        )
    n = cfg["points"][0]["n_total"]
    cm = data["cost_model"]
    tex = _TEX_TEMPLATE.format(
        config=_HEADLINE_CONFIG,
        n=n,
        cloud_acc=data["cloud_accuracy"],
        mode=data["cloud_accuracy_mode"],
        cost_q=data["cost_per_deferred_query_usd"],
        price_in=cm["price_in_per_mtok"],
        price_out=cm["price_out_per_mtok"],
        pure_local=cfg["pure_local_accuracy"],
        pure_cloud=cfg["pure_cloud_accuracy"],
        rows="\n".join(rows),
    )
    out = out_dir / "table13_deferral.tex"
    out.write_text(tex, encoding="utf-8")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("json_path", type=Path, help="deferral_economics.json")
    ap.add_argument("-o", "--output", type=Path, default=None,
                    help="output dir (default: alongside the JSON)")
    args = ap.parse_args()

    data = json.loads(args.json_path.read_text(encoding="utf-8"))
    out_dir = args.output or args.json_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    if _HEADLINE_CONFIG not in data["configs"]:
        raise SystemExit(f"config {_HEADLINE_CONFIG!r} not in JSON "
                         f"(have: {list(data['configs'])})")

    png = _plot(data, out_dir)
    tex = _table(data, out_dir)
    print(f"Wrote {png}")
    print(f"Wrote {out_dir / 'risk_coverage.pdf'}")
    print(f"Wrote {tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
